name = "backend"
compatibility_date = "2024-09-20"
compatibility_flags = [ "nodejs_compat" ]

[vars]
secretKey = "Vinit123"
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYzVlZTk1ZTEtZDEyMC00ZTJjLWJhZjYtMTE1NTZhMjU3OGYxIiwidGVuYW50X2lkIjoiOWZhZDFlMmJkYmZhN2YxNjkyMzRiYmNmM2YzOTZiMjYyMjdhZTc2MTY2YjFmOTkzMDk2MDI4ZjQ5NjNmMjkxOSIsImludGVybmFsX3NlY3JldCI6ImE1NjVjNmNjLTcyNjQtNDQ2NC1hNTVmLWMwYThlYWQxYTlhNCJ9.cer8K4BnOUeZCsK1wbL5FPjNHvxXKytC026jgBRtB0E"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"